# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
