# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0003_person_service'),
        ('events_list', '0003_userprofile'),
    ]

    operations = [
    ]
