# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0006_auto_20160301_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_1',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
