# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0008_event_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
