# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0009_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_applicable',
            field=models.BooleanField(default=True, help_text=b'Indicates if a person is applicable to our audience or not'),
        ),
    ]
