# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0010_person_is_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_hostname',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_1',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(default=b'', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(default=b'', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='service',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
