# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0011_auto_20160404_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meetupID', models.BigIntegerField(unique=True, verbose_name=b'Meetups.com ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_hostname',
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(related_name='people', to='events_list.Host'),
        ),
    ]
