# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0012_auto_20160405_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='eventname',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
