# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0013_host_eventname'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='largePhoto',
            field=models.URLField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='photo',
            field=models.URLField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='thumbnail',
            field=models.URLField(default=-1),
            preserve_default=False,
        ),
    ]
