# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0014_auto_20160411_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='city',
            field=models.CharField(default=-1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.CharField(default=-1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='fullName',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='service',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='state',
            field=models.CharField(default=-1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='topics',
            field=models.ManyToManyField(related_name='hosts', to='events_list.Topic'),
        ),
    ]
