# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0016_auto_20160411_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='event_link',
            field=models.URLField(default=b''),
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='host',
            name='url',
            field=models.URLField(default=b''),
        ),
    ]
